export interface BiomarkersInfo {
    id: string
    requestId: string
    clinicalSetting: string
    priorCAD: boolean
    age: number
    ageUnit: string
    sex: string
    height: number
    heightUnit: string
    weight: number
    weightUnit: string
    chestpain: string
    nicotine: string
    diabetes: string
    statin: boolean
    tcagginhibitor: boolean
    aceinhibitor: boolean
    calciumant: boolean
    betablocker: boolean
    diuretic: boolean
    nitrate: boolean
    systolicbp: number
    systolicbpUnit: string
    diastolicbp: number
    diastolicbpUnit: string
    qwave: string
    amylasep: number
    amylasepUnit: string
    alkaline: number
    alkalineUnit: string
    hstroponint: number
    hstroponintUnit: string
    alat: number
    alatUnit: string
    glucose: number
    glucoseUnit: string
    bilirubin: number
    bilirubinUnit: string
    urea: number
    ureaUnit: string
    uricacid: number
    uricacidUnit: string
    cholesterol: number
    cholesterolUnit: string
    hdl: number
    hdlUnit: string
    ldl: number
    ldlUnit: string
    protein: number
    proteinUnit: string
    albumin: number
    albuminUnit: string
    leukocyte: number
    leukocyteUnit: string
    mchc: number
    mchcUnit: string
    createdOn: Date
  }